### ISSUE TITLE
Augment the pr-body.md with actual.

### ISSUE THREAD

**Issue by boennemann** [hoodiehq/bundle-bump-bot#2]
Right now the pull request that gets created for a breaking change has always the same body, but we could augment it with some more useful information right from the package.json.

I'd suggest to just add [`lodash.template`](https://lodash.com/docs#template) as a dependency and to put these `<%=`, `%>` template delimiters directly into the `pr-body.md` file.

Before [passing it's contents to the GitHub API](https://github.com/hoodiehq/bundle-bump-bot/blob/master/index.js#L40) we could then run it through `template` and insert data from the package.

Before

> A hoodie component just released a new major version.

After

> `hoodie-server` just released the new major version 6.0.0.

Given that with the name of the package github urls are predictable we could even link `hoodie-server` to the repository, and `6.0.0` to the changelog `https://github.com/hoodiehq/hoodie-server/releases/tag/v6.0.0`.

There are even more place where it would make sense to add data, so just do as much as you like.

To test this out locally it should suffice to just run the template through this package's own data.

E.g. add a temporary `demo.js`

``` js
var fs = require('fs')
var template = require('lodash.template')
var pkg = require('./package.json')

var body = template(
  fs.readFileSync(path.join(__dirname, 'pr-body.md')).toString()
)(pkg)

console.log(body)
```

`node demo`

**Comment by boennemann** [comment]
For linking up things I'd like to show up another (better) way.
If the `package.json` contains a ["repository.url"](https://github.com/hoodiehq/bundle-bump-bot/blob/master/package.json#L26) we just use that for linking things up. That makes predicting URL's less fragile. We should run the "repository.url" through a [normalization](https://github.com/tj/node-github-url-from-git) first though.

**Comment by varjmes** [comment]
This has been done so I will close it. But if anyone comes accross this, please feel free to do some improvements and additions!

This work taught me that: Small modules from npm are ace, I like that I could just take the templating part of lodash ([lodash.template](https://www.npmjs.com/package/lodash.template)) and put it to work instead of taking the entire framework.

:balloon:
